/*
 * This file is generated by jOOQ.
 */
package com.nc.contentsaver.processes.saving.model.tables.records;


import com.nc.contentsaver.processes.saving.model.tables.DataLink;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataLinkRecord extends UpdatableRecordImpl<DataLinkRecord> implements Record4<String, String, Boolean, Integer> {

    private static final long serialVersionUID = -225161709;

    /**
     * Setter for <code>public.data_link.link</code>.
     */
    public void setLink(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.data_link.link</code>.
     */
    public String getLink() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.data_link.hash</code>.
     */
    public void setHash(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.data_link.hash</code>.
     */
    public String getHash() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.data_link.saved</code>.
     */
    public void setSaved(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.data_link.saved</code>.
     */
    public Boolean getSaved() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.data_link.copy_id</code>.
     */
    public void setCopyId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.data_link.copy_id</code>.
     */
    public Integer getCopyId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, Boolean, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, Boolean, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DataLink.DATA_LINK.LINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DataLink.DATA_LINK.HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return DataLink.DATA_LINK.SAVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return DataLink.DATA_LINK.COPY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component3() {
        return getSaved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCopyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getSaved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCopyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataLinkRecord value1(String value) {
        setLink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataLinkRecord value2(String value) {
        setHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataLinkRecord value3(Boolean value) {
        setSaved(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataLinkRecord value4(Integer value) {
        setCopyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataLinkRecord values(String value1, String value2, Boolean value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataLinkRecord
     */
    public DataLinkRecord() {
        super(DataLink.DATA_LINK);
    }

    /**
     * Create a detached, initialised DataLinkRecord
     */
    public DataLinkRecord(String link, String hash, Boolean saved, Integer copyId) {
        super(DataLink.DATA_LINK);

        set(0, link);
        set(1, hash);
        set(2, saved);
        set(3, copyId);
    }
}
