/*
 * This file is generated by jOOQ.
 */
package com.nc.contentsaver.processes.managing.model;


import com.nc.contentsaver.processes.managing.model.tables.DataCopyLink;
import com.nc.contentsaver.processes.managing.model.tables.DataLink;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DATA_COPY_LINK_PKEY = Indexes0.DATA_COPY_LINK_PKEY;
    public static final Index DATA_LINK_PKEY = Indexes0.DATA_LINK_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DATA_COPY_LINK_PKEY = Internal.createIndex("data_copy_link_pkey", DataCopyLink.DATA_COPY_LINK, new OrderField[] { DataCopyLink.DATA_COPY_LINK.ID }, true);
        public static Index DATA_LINK_PKEY = Internal.createIndex("data_link_pkey", DataLink.DATA_LINK, new OrderField[] { DataLink.DATA_LINK.LINK }, true);
    }
}
