/*
 * This file is generated by jOOQ.
 */
package com.nc.contentsaver.processes.managing.model;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.data_copy_link_seq</code>
     */
    public static final Sequence<Long> DATA_COPY_LINK_SEQ = new SequenceImpl<Long>("data_copy_link_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
