/*
 * This file is generated by jOOQ.
 */
package com.nc.contentsaver.processes.saving.model;


import com.nc.contentsaver.processes.saving.model.tables.DataCopyLink;
import com.nc.contentsaver.processes.saving.model.tables.DataLink;
import com.nc.contentsaver.processes.saving.model.tables.records.DataCopyLinkRecord;
import com.nc.contentsaver.processes.saving.model.tables.records.DataLinkRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DataCopyLinkRecord, Integer> IDENTITY_DATA_COPY_LINK = Identities0.IDENTITY_DATA_COPY_LINK;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DataCopyLinkRecord> DATA_COPY_LINK_PKEY = UniqueKeys0.DATA_COPY_LINK_PKEY;
    public static final UniqueKey<DataLinkRecord> DATA_LINK_PKEY = UniqueKeys0.DATA_LINK_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<DataLinkRecord, DataCopyLinkRecord> DATA_LINK__DATA_LINK_COPY_ID_FKEY = ForeignKeys0.DATA_LINK__DATA_LINK_COPY_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<DataCopyLinkRecord, Integer> IDENTITY_DATA_COPY_LINK = Internal.createIdentity(DataCopyLink.DATA_COPY_LINK, DataCopyLink.DATA_COPY_LINK.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DataCopyLinkRecord> DATA_COPY_LINK_PKEY = Internal.createUniqueKey(DataCopyLink.DATA_COPY_LINK, "data_copy_link_pkey", DataCopyLink.DATA_COPY_LINK.ID);
        public static final UniqueKey<DataLinkRecord> DATA_LINK_PKEY = Internal.createUniqueKey(DataLink.DATA_LINK, "data_link_pkey", DataLink.DATA_LINK.LINK);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<DataLinkRecord, DataCopyLinkRecord> DATA_LINK__DATA_LINK_COPY_ID_FKEY = Internal.createForeignKey(Keys.DATA_COPY_LINK_PKEY, DataLink.DATA_LINK, "data_link__data_link_copy_id_fkey", DataLink.DATA_LINK.COPY_ID);
    }
}
