/*
 * This file is generated by jOOQ.
 */
package com.nc.contentsaver.processes.saving.model;


import com.nc.contentsaver.processes.saving.model.tables.DataCopyLink;
import com.nc.contentsaver.processes.saving.model.tables.DataLink;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.data_copy_link</code>.
     */
    public static final DataCopyLink DATA_COPY_LINK = com.nc.contentsaver.processes.saving.model.tables.DataCopyLink.DATA_COPY_LINK;

    /**
     * The table <code>public.data_link</code>.
     */
    public static final DataLink DATA_LINK = com.nc.contentsaver.processes.saving.model.tables.DataLink.DATA_LINK;
}
